---
# tasks file for deploy_flask
-  name: install python3 + pip 
   dnf:
     name: 
       - python3
       - python3-pip

     state: present


-  name: create group
   group:
     name: "{{ group }}"

-  name: create flask user and group
   user:
     name: "{{ user }}"
     group: "{{ group }}"
     createhome: no
     shell: /sbin/nologin

-  name: create flask app directory
   file:
     path: "{{ app_dir }}"
     state: directory
     owner: "{{ user }}"
     group: "{{ group }}"
     mode: "0755"

- name: create virtualenv
  command: python3 -m venv {{ app_dir }}/venv
  args:
    creates: "{{ app_dir }}/venv"
    

-  name: create virtualenv and install flask
   pip:
     virtualenv: "{{ app_dir }}/venv"
     name: flask  

-  name: app.py template
   template:
     src: "app.py.j2"
     dest: "{{ app_dir }}/app.py"

-  name: flask service template
   template:
     src: "flask_app.service.j2"
     dest: "/etc/systemd/system/{{ service_name }}.service"
   notify: restart flask service

- name: reload systemd daemon
  systemd:
    daemon_reload: true

-  name: start flask service
   service:
     name: "{{ service_name }}"
     state: started
     enabled: true  